# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddingandremovingitemsfromthecart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addingandremovingitemsfromthecart(self):
    # Test name: adding and removing items from the cart
    # Step # | name | target | value
    # 1 | open | /ua/ | 
    self.driver.get("https://makeup.com.ua/ua/")
    # 2 | setWindowSize | 1792x1033 | 
    self.driver.set_window_size(1792, 1033)
    # 3 | click | linkText=Парфумерія | 
    self.driver.find_element(By.LINK_TEXT, "Парфумерія").click()
    # 4 | runScript | window.scrollTo(0,10) | 
    self.driver.execute_script("window.scrollTo(0,10)")
    # 5 | runScript | window.scrollTo(0,394) | 
    self.driver.execute_script("window.scrollTo(0,394)")
    # 6 | runScript | window.scrollTo(0,417) | 
    self.driver.execute_script("window.scrollTo(0,417)")
    # 7 | click | id=popularinput-checkbox-2243-30649 | 
    self.driver.find_element(By.ID, "popularinput-checkbox-2243-30649").click()
    # 8 | click | id=popularinput-checkbox-2245-122923 | 
    self.driver.find_element(By.ID, "popularinput-checkbox-2245-122923").click()
    # 9 | click | css=.simple-slider-list-buttons:nth-child(2) > .button | 
    self.driver.find_element(By.CSS_SELECTOR, ".simple-slider-list-buttons:nth-child(2) > .button").click()
    # 10 | click | css=.align-center > .button | 
    self.driver.find_element(By.CSS_SELECTOR, ".align-center > .button").click()
    # 11 | click | css=.product__button-remove:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".product__button-remove:nth-child(3)").click()
  
